spring:
  profiles:
    active: local
    include: secret

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000

  data:
    redis:
      port: 6379
      host: localhost

  cloud:
    gcp:
      credentials:
        location: ${cloud.gcp.credentials.location}
      project-id: ${cloud.gcp.project-id}
      bucket: ${cloud.gcp.bucket}

security:
  jwt:
    token:
      secret-key: test
      expire-length: 3600000
      algorithm: HS256

# local 환경
cookie:
  access-token-key: token
  http-only: false
  secure: false
  domain: localhost
  path: /
#  same-site: none
  same-site: Lax
  max-age: 7200 #2시간